### ISSUE TITLE
Qreport Issue

### ISSUE THREAD

**Issue by phoebe460** [jengelmann/FastqPuri#4]
Hi, I've been trying to use your package which I successfully downloaded using bioconda, but I am having issues when I am actually using the Qreport function with the example files that were included.

For instance, I type in the following script on the command line:
$ Qreport -i /FastqPuri-1.0.6/examples/Qreport_Sreport/test.fq.bz2 -l 51 -o test_report_out

My output is: 
- Read length: 51
- Number of tiles: 96
- Min quality: 27
- Qualities for properties plot: 27,33,37
- Output bin-file : test_report_out.bin
- Output html-file : test_report_out.html
- Output info-file: test_report_out.info
Starting Qreport at: Sat Oct  5 18:17:20 2019
- Reading a filtered file? no.
Illegal instruction (core dumped)

Would you know how to resolve the 'Ilegal instruction (core dumped)' issue here? I know I've inputted all the required flags correctly, but I am still getting the same error. If there is anyway you could help me, then that would be awesome.

Thanks!

**Comment by clottaz** [comment]
Hi,
Thanks for your interest in our package. Unfortunatly, I was not yet able to fix this issue. I have no simpler suggestion than just compiling FastqPuri on your machine on your own. I hope this is feasible for you.

Kind regards,
.

>>> phoebe460 <notifications@github.com> 05.10.2019 20:24 >>>
Hi, I've been trying to use your package which I successfully downloaded using bioconda, but I am having issues when I am actually using the Qreport function with the example files that were included.

For instance, I type in the following script on the command line:
$ Qreport -i /FastqPuri-1.0.6/examples/Qreport_Sreport/test.fq.bz2 -l 51 -o test_report_out

My output is: 
- Read length: 51
- Number of tiles: 96
- Min quality: 27
- Qualities for properties plot: 27,33,37
- Output bin-file : test_report_out.bin
- Output html-file : test_report_out.html
- Output info-file: test_report_out.info
Starting Qreport at: Sat Oct  5 18:17:20 2019
- Reading a filtered file? no.
Illegal instruction (core dumped)

Would you know how to resolve the 'Ilegal instruction (core dumped)' issue here? I know I've inputted all the required flags correctly, but I am still getting the same error. If there is anyway you could help me, then that would be awesome.

Thanks!

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/jengelmann/FastqPuri/issues/4

**Comment by jengelmann** [comment]
Hi Phoebe,
thanks for your interest in FastqPuri and your messages. What is your operating system?
Best,
Julia

On 05.10.2019 20:24, phoebe460 wrote:

Hi, I've been trying to use your package which I successfully downloaded using bioconda, but I am having issues when I am actually using the Qreport function with the example files that were included.

For instance, I type in the following script on the command line:
$ Qreport -i /FastqPuri-1.0.6/examples/Qreport_Sreport/test.fq.bz2 -l 51 -o test_report_out

My output is:

  *   Read length: 51
  *   Number of tiles: 96
  *   Min quality: 27
  *   Qualities for properties plot: 27,33,37
  *   Output bin-file : test_report_out.bin
  *   Output html-file : test_report_out.html
  *   Output info-file: test_report_out.info
Starting Qreport at: Sat Oct 5 18:17:20 2019
  *   Reading a filtered file? no.
Illegal instruction (core dumped)

Would you know how to resolve the 'Ilegal instruction (core dumped)' issue here? I know I've inputted all the required flags correctly, but I am still getting the same error. If there is anyway you could help me, then that would be awesome.

Thanks!

**Comment by phoebe460** [comment]
Hi, I am currently using a Linux based operating system (I believe it is 64 bit). You mentioned there is a way to use the program directly on my computer on my own. How is that possible? Is there a tutorial I could follow? If you can let me know, then that would be awesome. Thank you again!

**Comment by clottaz** [comment]
Hi, 
After "git clone https://github.com/jengelmann/FastqPuri.git" fetches the needed files on your computer. README.md explains the local compilation.
Cheers,
Claudio


>>> phoebe460 <notifications@github.com> 07.10.2019 17:29 >>>
Hi, I am currently using a Linux based operating system (I believe it is 64 bit). You mentioned there is a way to use the program directly on my computer on my own. How is that possible? Is there a tutorial I could follow? If you can let me know, then that would be awesome. Thank you again!

**Comment by jengelmann** [comment]
Hi Phoebe,
sorry for the late reply. Have you tried the docker or singularity container (described in the README.md)? They should work better than the bioconda solution, which is still in development.
Thanks and cheers,
Julia

**Comment by Diango700** [comment]
Hello all, 
your package can be verry interesting if can you do the exemple command line for each step

**Comment by phoebe460** [comment]
Hi everyone! First off, I am sorry about not responding for a really long time. I didn't realize I never closed this issue.. Unfortunately, I am no longer working on the project that uses this tool before, but if I come back to it and seems useful for the current project I am working on, I will definitely ask more questions. Thank you all for your help and happy new year!
